// Tipos tratados pelos reducers para definir qual ação (actions) tomar.

export const CART_ADD_PRODUCT_SUCCESS = 'CART_ADD_PRODUCT_SUCCESS';
export const CART_ADD_PRODUCT_REQUEST = 'CART_ADD_PRODUCT_REQUEST';
export const CART_ADD_PRODUCT_FAILURE = 'CART_ADD_PRODUCT_FAILURE';

export const PRODUCTS_GETALL_SUCCESS = 'PRODUCTS_GETALL_SUCCESS';
export const PRODUCTS_GETALL_REQUEST = 'PRODUCTS_GETALL_REQUEST';
export const PRODUCTS_GETALL_FAILURE = 'PRODUCTS_GETALL_FAILURE';